### ISSUE TITLE
Update to version 0.11.2

### ISSUE THREAD

**Issue by jokay** [unclev/prosody-docker-extended#9]
Hello

Any plans to update to the current version [0.11.2](https://prosody.im/doc/release/0.11.2) of [prosody](https://prosody.im)?

**Comment by unclev** [comment]
@x-jokay, thank you for pointing on the issue.

Due to the bug #11 in `check_prosody_update` it didn't automatically switch to 0.11.2 in `stable`.

The image `unclev/prosody-docker-extended:stable` on [DockerHub](https://hub.docker.com/r/unclev/prosody-docker-extended/builds) has been updated, and contains 0.11.2 now. To verify:

```shell
docker run --rm --user root unclev/prosody-docker-extended:stable prosody
```

You may also try `unclev/prosody-docker-extended:0.11` for `0.11` nightly builds.

**Comment by jokay** [comment]
Thank you very much :tada:
